config/routes.rb
Rails.application.routes.draw do
  root 'properties#index'
  resources :properties
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/property.rb
class Property < ApplicationRecord
  validates :property_id, presence: true, uniqueness: true
  validates :name, presence: true
  validates :email, presence: true
  validates :unit_bedrooms, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[show edit update destroy]

  # static photo lists
  INTERIOR_PHOTOS = [
    "https://images.rentable.co/125174/72525196/large.jpeg",
    "https://images.rentable.co/125174/72526105/large.jpeg",
    "https://images.rentable.co/102207/82056855/large.jpeg",
    "https://images.rentable.co/125174/72527744/large.jpeg"
  ].freeze

  EXTERIOR_PHOTOS = [
    "https://images.rentable.co/125174/72525707/large.jpeg",
    "https://images.rentable.co/102207/82630648/large.jpeg",
    "https://images.rentable.co/102207/77019634/large.jpeg",
    "https://images.rentable.co/102207/88573201/large.jpeg"
  ].freeze

  # GET /properties or /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1 or /properties/1.json
  def show
    @property = Property.find(params[:id])

    # default to "interior" if param is missing or invalid
    view = params[:images].to_s.downcase
    view = %w[interior exterior].include?(view) ? view : "interior"

    @images = (view == "exterior" ? EXTERIOR_PHOTOS : INTERIOR_PHOTOS)
  end

  # GET /properties/new
  def new
    ImportPropertiesJob.perform_later
    redirect_to properties_path, notice: 'Import started!'

    # @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties or /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: "Property was successfully created." }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    @property.destroy!

    respond_to do |format|
      format.html { redirect_to properties_path, status: :see_other, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_property
    @property = Property.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def property_params
    params.require(:property).permit(:property_id, :name, :email, :unit_bedrooms)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdoboFeed</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/properties/_form.html.erb
<%= form_with(model: property) do |form| %>
  <% if property.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :property_id, style: "display: block" %>
    <%= form.text_field :property_id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :unit_bedrooms, style: "display: block" %>
    <%= form.text_field :unit_bedrooms %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/properties/_property.html.erb
<div id="<%= dom_id property %>">
  <p>
    <strong>Property:</strong>
    <%= property.property_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= property.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= property.email %>
  </p>

  <p>
    <strong>Unit bedrooms:</strong>
    <%= property.unit_bedrooms %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= property.description%>
  </p>

</div>

app/views/properties/edit.html.erb
<h1>Editing property</h1>

<%= render "form", property: @property %>

<br>

<div>
  <%= link_to "Show this property", @property %> |
  <%= link_to "Back to properties", properties_path %>
</div>

app/views/properties/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="text-[#1A0935] w-full min-h-screen flex flex-col justify-start items-center">
  <div class="bg-[#1A0935] h-12 w-full text-white flex flex-row justify-between items-center px-24 py-12">
    <img src="https://www.hiremaven.ai/wp-content/uploads/2025/02/logo-maven-ai.svg" alt="logo" class="w-32"/>
    <div>
      <%= link_to "Import Properties", new_property_path, class: "" %>
    </div>
  </div>

  <div class="w-full flex flex-col justify-center items-start gap-6 mb-8">
    <div class="text-5xl font-medium text-left w-full px-8 pt-12">Properties</div>
    <div class="w-full px-8 flex justify-center items-center">
      <div class="w-full h-[1px] bg-[#1A0935] mt-4 mb-2"></div>
    </div>
    <div id="properties" class="w-full grid grid-cols-1 md:grid-cols-4 gap-4 mt-4 px-8">
      <% @properties.each do |property| %>
        <div class="bg-[#1A0935] text-white p-8 rounded-lg">
          <%= render property %>
          <p class="mt-2 w-full flex justify-start items-start">
            <%= link_to "Show this property", property, class: "bg-white px-4 py-2 rounded-full text-[#1A0935]" %>
          </p>
        </div>
      <% end %>
    </div>
  </div>
   
</div>
<div class="w-full px-24 py-12 bg-[#1A0935] text-white/75 flex flex-col justify-start items-start">
    <img src="https://www.hiremaven.ai/wp-content/uploads/2025/02/logo-maven-ai.svg" alt="logo" class="w-40"/>
    <div class="w-full h-[1px] bg-white/20 mt-4 mb-2"></div>
    <p>©2025 MavenAI. All rights reserved.</p>
</div>

app/views/properties/new.html.erb
<h1>New property</h1>

<%= render "form", property: @property %>

<br>

<div>
  <%= link_to "Back to properties", properties_path %>
</div>

app/views/properties/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="text-[#1A0935] w-full min-h-screen flex flex-col justify-start items-center">
  <div class="bg-[#1A0935] h-12 w-full text-white flex flex-row justify-between items-center px-24 py-12">
    <img src="https://www.hiremaven.ai/wp-content/uploads/2025/02/logo-maven-ai.svg" alt="logo" class="w-32"/>
    <div>
      <%= link_to "Back to properties", properties_path %>
    </div>
  </div>

  <div class="w-full flex flex-col justify-center items-start gap-6">
    <div class="text-5xl font-medium text-left w-full px-8 pt-12">Property</div>
    <div class="w-full px-8 flex justify-center items-center">
      <div class="w-full h-[1px] bg-[#1A0935] mt-4 mb-2"></div>
    </div>
    <div class="px-8">
      <% current = params[:images] || "interior" %>
      
      <%= link_to "Interior",
          property_path(@property, images: "interior"),
          class: [
            "px-4 py-2 rounded-full",
            current == "interior" ?
              "text-[#1A0935] bg-white border border-[#1A0935]" :
              "text-white bg-[#1A0935]"
          ].join(" ")
      %>
      
      <%= link_to "Exterior",
          property_path(@property, images: "exterior"),
          class: [
            "px-4 py-2 rounded-full",
            current == "exterior" ?
              "text-[#1A0935] bg-white border border-[#1A0935]" :
              "text-white bg-[#1A0935]"
          ].join(" ")
      %>
    </div>
    <div class="w-full grid md:grid-cols-4 grid-cols-1 gap-4 px-8">
      <% @images.each do |url| %>
        <%= image_tag url, class: "rounded shadow-md" %>
      <% end %> 
    </div>
    <div id="properties" class="w-full flex flex-col justify-start items-start gap-4 mt-4 px-8">
      <%= render @property %>
  
      <div class="flex flex-col justify-start items-start gap-4">
        <%= link_to "Edit this property", edit_property_path(@property), class: "px-4 py-2 text-white bg-[#1A0935] rounded-full" %>
  
        <%= button_to "Destroy this property", @property, method: :delete, class: "px-4 py-2 text-white bg-[#1A0935] rounded-full"%>
      </div>
    </div>
  </div>
  
  
</div>
<div class="w-full px-24 py-12 bg-[#1A0935] text-white/75 flex flex-col justify-start items-start">
    <img src="https://www.hiremaven.ai/wp-content/uploads/2025/02/logo-maven-ai.svg" alt="logo" class="w-40"/>
    <div class="w-full h-[1px] bg-white/20 mt-4 mb-2"></div>
    <p>©2025 MavenAI. All rights reserved.</p>
</div>